#pragma once

//
// This file contains all IDs of game assets 
//

#pragma region OBJECT TYPE
#define OBJECT_TYPE_MARIO_GOING_INTO_PIPE_EFFECT -12
#define OBJECT_TYPE_POWER_METER -11
#define OBJECT_TYPE_CARD -10
#define OBJECT_TYPE_TEXT -9
#define OBJECT_TYPE_ROULETTE_CARD_EFFECT -8
#define OBJECT_TYPE_MARIO_TAIL -7
#define OBJECT_TYPE_BROKEN_BRICK_EFFECT -6
#define OBJECT_TYPE_P_SWITCH -5
#define OBJECT_TYPE_SCORE_TEXT -4
#define OBJECT_TYPE_SUPER_LEAF -3
#define OBJECT_TYPE_BULLET -2
#define OBJECT_TYPE_MUSHROOM -1
#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_PARA_GOOMBA	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_DECORATED 6
#define OBJECT_TYPE_REWARDING_BRICK 7
#define OBJECT_TYPE_INVINSIBLE_BRICK 8
#define OBJECT_TYPE_PLATFORM_TOP_ONLY 9
#define OBJECT_TYPE_VENUS_FIRE_TRAP 10
#define OBJECT_TYPE_KOOPA 11
#define OBJECT_TYPE_PARA_KOOPA 12
#define OBJECT_TYPE_PIRANHA_PLANT 13
#define OBJECT_TYPE_SWITCH_BRICK 14
#define OBJECT_TYPE_GOAL 15
#define OBJECT_TYPE_WORLD_MAP_NODE 16
#define OBJECT_TYPE_MARIO_WORLD_MAP 17
#define OBJECT_TYPE_TITLE_MENU 18
#define OBJECT_TYPE_HUD 19
#define OBJECT_TYPE_PORTAL	50
#define OBJECT_TYPE_PORTAL_WORLD_MAP 51
#define OBJECT_TYPE_PORTAL_HIDDEN_ZONE 52
#pragma endregion

#pragma region MARIO LEVEL
#define	MARIO_LEVEL_SMALL	1
#define	MARIO_LEVEL_BIG		2
#define MARIO_LEVEL_RACCOON 3
#pragma endregion